"""initial

Revision ID: a495682d4611
Revises: 
Create Date: 2024-10-22 15:51:03.441550

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a495682d4611"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baseuser",
        sa.Column("id_bu", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uu_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("father_name", sa.VARCHAR(length=32), nullable=True),
        sa.Column("email", sa.VARCHAR(length=64), nullable=False),
        sa.Column("password", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("photo", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id_bu"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("uu_id"),
    )
    op.create_table(
        "admin",
        sa.Column("id_a", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("baseuser", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["baseuser"], ["baseuser.id_bu"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_a"),
        sa.UniqueConstraint("baseuser"),
    )
    op.create_table(
        "user",
        sa.Column("id_u", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("about", sa.VARCHAR(length=255), nullable=True),
        sa.Column("baseuser", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["baseuser"], ["baseuser.id_bu"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_u"),
        sa.UniqueConstraint("baseuser"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("admin")
    op.drop_table("baseuser")
    # ### end Alembic commands ###
